steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/palmoapp:latest', '-t', 'gcr.io/$PROJECT_ID/palmoapp:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/palmoapp:$BUILD_ID', '.']
  id: 'build-image-palmoapp'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
images:
- 'gcr.io/$PROJECT_ID/palmoapp:latest'
- 'gcr.io/$PROJECT_ID/palmoapp:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/palmoapp:$BUILD_ID'
