steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/palmoapp:latest', '-t', 'gcr.io/$PROJECT_ID/palmoapp:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/palmoapp:$BUILD_ID', '.']
  id: 'build-image-palmoapp'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/palmoapp:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-palmoapp']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'palmoappservice'
  - '--image'
  - 'gcr.io/$PROJECT_ID/palmoapp:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
  id: 'deploy-to-cloud-run'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  volumes:
  - name: 'vol1'
    path: '/nodeappvolume'
  entrypoint: '/bin/bash'
  args: ['-c', 'gcloud builds log $BUILD_ID > /nodeappvolume/buildlog.log']
  waitFor: ['deploy-to-cloud-run']
  id: 'fetch-build-log'
- name: 'bash'
  volumes:
  - name: 'vol1'
    path: '/nodeappvolume'
  args: ['tar', '-czvf', 'artifacts.tar.gz', 'views', '/nodeappvolume/buildlog.log']
  waitFor: ['fetch-build-log']
  id: 'create-artifacts-zip'
options:
  logging: GCS_ONLY

images:
- 'gcr.io/$PROJECT_ID/palmoapp:latest'
- 'gcr.io/$PROJECT_ID/palmoapp:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/palmoapp:$BUILD_ID'
artifacts:
  objects:
    location: 'gs://devops-$PROJECT_ID/$BUILD_ID'
    paths: ['artifacts.tar.gz']
